### ISSUE TITLE
exception during malloc

### ISSUE THREAD

**Issue by asdfstuart** [ghjwp7/yume3#6]
stuart@stuart-G74SX:~/src/yume/yume3$ Ymalloc 24 ./src/yume3.c 108 
Ymalloc 12 ./src/yume3.c 109 
Ymalloc 24 ./src/yume3.c 128 
Ymalloc 21 ./src/yume3.c 131 
Ymalloc 2048 ./src/yume3-util.c 99 
Ymalloc 7168 ./src/yume3-p1.c 364 
Ymalloc 2048 ./src/yume3-p1.c 369 
yume3: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

kludged a fix by modifying yume3-util.c:
void *Ymalloc(size_t size, char *F, int L) {
	printf("Ymalloc %d %s %d \n", size, F, L);
	fflush(stdout);
	//  void *t = malloc(size);
  void *t = malloc(size + 17);
  if (!t) malloc_errorExit(F, L, size);
  return t;
}

**Comment by ghjwp7** [comment]
Compiled a branch with -fsanitizer=address to use AddressSanitizer to find problem.  Found problem in yume3.c -- didn't account for null byte at end of string. Added 1 for that, after which yume runs ok although at termination AddressSanitizer reports indirect leaks which should be looked at.  Pushed fixes in master to github repo.
